name: safe_space_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  logger: ^2.4.0
  pedometer: ^4.0.2
  http: ^1.2.2
  geolocator: ^9.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.0.20
  provider: ^6.0.0
  firebase_app_check: ^0.3.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_background.png
    - assets/images/loginback2.png
